name: vibrio-surveillance

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - nextflow
  - fastp
  - bwa-mem2
  - samtools=1.24
  - bcftools=1.24
  - htslib=1.24
  - ncbi-amrfinderplus
  - blast
  - bc
